"""User-editable radio configuration for the 2025-05-03 event."""

from __future__ import annotations

from solar_apps.workflows.radio.configs._path_overrides import (
    apply_event_path_overrides,
)

__all__ = [
    "AIA_MULTI_WAVE_RAW_RADIO_SPECTROGRAM_CONFIG",
    "AIA_RADIO_HMI_CONFIG",
    "AIA_RAW_RADIO_SPECTROGRAM_CONFIG",
    "DRIFT_SELECTION_PRODUCT_CONFIG",
    "EVENT_CONFIG",
    "NEWKIRK_CONFIG",
    "NEWKIRK_HEIGHT_COMPARISON_CONFIG",
    "OUTPUT_CONFIG",
    "RADIO_DIAGNOSTIC_PRESENTATION_CONFIG",
    "USER_CONFIG",
]


OUTPUT_CONFIG = {
    # Common output controls used by both radio entrypoints.
    "output_dir": "outputs/radio/2025-05-03",
    "analysis_subdir": "auto",
    "gaussian_diagnostics_csv": "radio_gaussian_fit_diagnostics.csv",
    "valid_centers_csv": "radio_gaussian_valid_centers.csv",
    "newkirk_csv": "radio_gaussian_newkirk_extrapolated.csv",
    "drift_speed_csv": "radio_drift_newkirk_speed.csv",
    "drift_selection_subdir": "drift_selection",
    "enable_static_summary": False,
    "enable_html_dashboard": False,
}

USER_CONFIG = {
    "mode": "multi_band",
    "study_mode": "exploratory",
    "data": {
        "multi_band_root": "data/radio/2025-05-03",
        "multi_band_freqs": [149, 164, 190, 205, 223, 238],
        "polarization": "RR+LL",
        "single_file_path": "data/radio/2025-05-03/149MHz/RR/example.fits",
        "data_dir": "data/radio/2025-05-03/149MHz/RR",
        "start_idx": 648,
        "end_idx": 944,
        "multi_band_time_tolerance_seconds": 0.1,
    },
    "features": {
        "gaussian_overlay": True,
        "spectrogram_panel": True,
        "background_correction": False,
        "save_gaussian_diagnostics": True,
        "save_background_products": False,
        "save_individual_pols": False,
        "raw_quality_filter": True,
    },
    "display": {
        "use_custom_lim": True,
        "custom_xlim": (-1500, 1500),
        "custom_ylim": (-1500, 1500),
        "radio_cmap": "hot",
        "background_bad_color": "#000080",
        "use_per_band_colormap": True,
        "per_band_range_method": "fixed_percentile",
        "per_band_percentiles": [99.7, 99.99],
        "preserve_fits_wcs_orientation": True,
        "radio_image_origin_mode": "auto",
        "draw_coordinate_corner_debug": False,
    },
    "gaussian": {
        "overlay_display_mode": "fwhm_only",
        "fit_use_source_mask": True,
        "fit_snr_threshold": 5.0,
        "fit_peak_fraction_threshold": 0.40,
        "fit_grow_peak_fraction_threshold": 0.22,
        "fit_mask_target_min_pixels": 18,
        "fit_mask_target_max_pixels": 260,
        "fit_min_mask_pixels": 8,
        "fit_peak_fraction_threshold_min": 0.25,
        "fit_peak_fraction_threshold_max": 0.62,
        "fit_peak_fraction_threshold_step": 0.03,
        "gaussian_source_mode": "multi",
        "multi_gaussian_source_count": None,
        "multi_gaussian_max_sources": 2,
        "multi_gaussian_min_peak_fraction": 0.16,
        "multi_gaussian_min_peak_distance_pixels": 2,
        "multi_gaussian_use_watershed": True,
        "draw_multi_gaussian_labels": True,
        "gaussian_per_band_params": {
            149: {
                "fit_peak_fraction_threshold": 0.38,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.55,
                "fit_mask_target_min_pixels": 18,
                "fit_mask_target_max_pixels": 180,
                "gaussian_fit_roi_padding_pixels": 4,
                "gaussian_fit_max_pixels": 350,
                "max_sigma_fraction": 0.17,
                "fit_background_model": "constant",
                "fit_mask_dilation_pixels": 1,
                "gaussian_max_center_peak_distance_fraction_of_fwhm": 0.65,
            },
            164: {
                "fit_peak_fraction_threshold": 0.38,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.55,
                "fit_mask_target_min_pixels": 18,
                "fit_mask_target_max_pixels": 180,
                "gaussian_fit_roi_padding_pixels": 4,
                "gaussian_fit_max_pixels": 350,
                "max_sigma_fraction": 0.17,
                "max_fwhm_arcsec": 400.0,
                "fit_background_model": "constant",
                "fit_mask_dilation_pixels": 1,
            },
            190: {
                "fit_peak_fraction_threshold": 0.40,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.60,
                "fit_mask_target_min_pixels": 18,
                "fit_mask_target_max_pixels": 220,
                "gaussian_fit_roi_padding_pixels": 4,
                "gaussian_fit_max_pixels": 400,
                "max_sigma_fraction": 0.18,
                "fit_background_model": "constant",
                "fit_mask_dilation_pixels": 1,
                "multi_gaussian_min_peak_distance_pixels": 1,
            },
            205: {
                "fit_peak_fraction_threshold": 0.40,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.60,
                "fit_mask_target_min_pixels": 18,
                "fit_mask_target_max_pixels": 240,
                "gaussian_fit_roi_padding_pixels": 4,
                "gaussian_fit_max_pixels": 400,
                "max_sigma_fraction": 0.18,
                "fit_background_model": "constant",
                "fit_mask_dilation_pixels": 1,
            },
            223: {
                "fit_peak_fraction_threshold": 0.42,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.65,
                "fit_mask_target_min_pixels": 16,
                "fit_mask_target_max_pixels": 180,
                "gaussian_fit_roi_padding_pixels": 3,
                "gaussian_fit_max_pixels": 320,
                "max_sigma_fraction": 0.16,
                "fit_background_model": "plane",
                "fit_mask_dilation_pixels": 1,
            },
            238: {
                "fit_peak_fraction_threshold": 0.42,
                "fit_peak_fraction_threshold_min": 0.25,
                "fit_peak_fraction_threshold_max": 0.65,
                "fit_mask_target_min_pixels": 16,
                "fit_mask_target_max_pixels": 180,
                "gaussian_fit_roi_padding_pixels": 3,
                "gaussian_fit_max_pixels": 320,
                "max_sigma_fraction": 0.16,
                "fit_background_model": "plane",
                "fit_mask_dilation_pixels": 1,
                "multi_gaussian_min_peak_fraction": 0.10,
            },
        },
        "max_fwhm_arcsec": 1800.0,
        "max_center_peak_distance_arcsec": 300.0,
        "draw_raw_peak_marker": False,
        "draw_fit_peak_distance": False,
        "draw_coordinate_debug": False,
        "gaussian_diagnostics_csv": OUTPUT_CONFIG["gaussian_diagnostics_csv"],
    },
    "background": {
        "mode": "off",
        "apply_to_display": False,
        "apply_to_fit": False,
        "apply_before_polarization_combine": False,
    },
    "spectrogram": {
        "file_paths": [
            "data/radio/2025-05-03/spectrogram-1.fits",
            "data/radio/2025-05-03/spectrogram-2.fits",
        ],
        "file_path": "data/radio/2025-05-03/spectrogram-1.fits",
        "time_display_mode": "user",
        "time_start": "2025-05-03T07:20:25",
        "time_end": "2025-05-03T07:22:25",
        "f_start": 80.0,
        "f_end": 300.0,
        "polarization": "sum",
        # With use_log10=True, vmin/vmax are log10 intensity limits.
        "vmin": 1.9,
        "vmax": 3.6,
        "use_log10": True,
        "cmap": "jet",
    },
    "drift_rate": {
        "enabled": True,
        "mode": "interactive_manual",
        "interactive": {
            "enabled": True,
            "host": "127.0.0.1",
            "port": 8050,
            "auto_open_browser": True,
            "launch_policy": "always",
            "reuse_existing_selection": True,
            "overwrite_selection": False,
            "print_usage_hint": True,
            "auto_increment_port": True,
            "max_port_tries": 20,
            "block_until_done": True,
            "selection_timeout_seconds": 0,
            "allow_multiple_lines": True,
            "click_pair_mode": "start_end",
            "show_crosshair": True,
            "show_live_coordinate": True,
            "show_preview_line": True,
            "line_color_cycle": [
                "white",
                "cyan",
                "lime",
                "magenta",
            ],
        },
        "selection_json": "spectrogram_drift_rate_manual_selection.json",
        "selection_preview_png": "drift_rate_selection_preview",
        "selection_metadata_json": "spectrogram_drift_rate_selection_metadata.json",
        "draw_lines": True,
        "draw_endpoints": True,
        "draw_label": True,
        "draw_selected_id": True,
        "label_format": "{label}: df/dt={drift_rate:.2f} MHz/s",
        "line_width": 2.2,
        "endpoint_marker": "o",
        "endpoint_size": 30,
        "save_drift_diagnostics": True,
        "drift_diagnostics_csv": "radio_spectrogram_drift_rate_diagnostics.csv",
    },
    "output": {
        "output_dir": OUTPUT_CONFIG["output_dir"],
        "analysis_subdir": OUTPUT_CONFIG["analysis_subdir"],
        "show_plot": False,
        "save_plot": True,
        "dpi": 300,
    },
}

AIA_RADIO_HMI_CONFIG = {
    "paths": {
        "radio_base_dir": "data/radio/2025-05-03",
        "aia_base_dir": "data/aia/2025-05-03/171",
        "hmi_base_dir": "data/hmi/2025-05-03",
        "output_dir": "outputs/radio/2025-05-03/AIA_Raw_Radio_Overlay",
    },
    "aia": {
        "wavelength": "171",
        "aia_wavelength": "171",
        "aia_file_start_idx": 104,
        "aia_file_end_idx": 116,
        "aia_vmin": 16,
        "aia_vmax": 6666,
        "aia_cmap": "sdoaia171",
    },
    "hmi": {
        "overlay_hmi": True,
        "hmi_time_threshold": 24,
        "hmi_threshold_gauss": 0.0,
        "hmi_sigma": 2,
        "hmi_levels_gauss": [100.0],
    },
    "radio": {
        "radio_overlay_mode": "raw",
        "selected_bands": [
            "149MHz",
            "164MHz",
            "190MHz",
            "205MHz",
            "223MHz",
            "238MHz",
        ],
        "polarization_mode": "RR+LL",
        "combine_polarizations": True,
        "rr_dir_suffix": "RR",
        "ll_dir_suffix": "LL",
        "weighted_average": False,
        "rr_weight": 0.5,
        "ll_weight": 0.5,
        "time_tolerance_seconds": 0.01,
        "radio_time_threshold": 6,
        "max_radio_per_band": 28,
        "radio_use_float32": True,
        "use_radec_maps": False,
    },
    "wcs_reproject": {
        "roi_bounds_arcsec": {
            "left": -800,
            "bottom": -200,
            "right": 0,
            "top": 600,
        },
        "use_radec_maps": False,
    },
    "gaussian": {
        "enable_gaussian_overlay": False,
        "draw_low_quality_gaussian_contours": False,
        "fit_use_source_mask": True,
        "fit_snr_threshold": 5.0,
        "fit_grow_snr_threshold": 3.0,
        "fit_peak_fraction_threshold": 0.40,
        "fit_grow_peak_fraction_threshold": 0.22,
        "fit_mask_target_min_pixels": 18,
        "fit_mask_target_max_pixels": 260,
        "fit_peak_fraction_threshold_min": 0.25,
        "fit_peak_fraction_threshold_max": 0.62,
        "fit_peak_fraction_threshold_step": 0.03,
        "fit_min_mask_pixels": 12,
        "fit_mask_dilation_pixels": 1,
        "gaussian_fit_use_roi": True,
        "gaussian_fit_roi_padding_pixels": 4,
        "gaussian_fit_max_pixels": 400,
        "gaussian_fit_normalize_data": True,
        "gaussian_fit_fallback_to_moment": True,
        "gaussian_fit_maxfev": 8000,
        "gaussian_fit_verbose": False,
        "fit_background_model": "constant",
        "max_sigma_fraction": 0.18,
        "max_fwhm_arcsec": 1800.0,
        "max_center_peak_distance_arcsec": 300.0,
        "gaussian_max_center_peak_distance_fraction_of_fwhm": 0.5,
        "gaussian_valid_only_for_overlay": True,
        "gaussian_valid_only_for_trajectory": True,
        "gaussian_allow_moment_fallback_for_trajectory": False,
        "save_gaussian_diagnostics": False,
        "gaussian_diagnostics_csv": "aia_radio_gaussian_fit_diagnostics.csv",
    },
    "display": {
        "show_radio_contours": True,
        "contour_levels_peak": [0.90],
        "contour_linewidths": [2.0],
        "contour_alpha": 0.90,
        "contour_smooth_sigma": 0,
        "mark_radio_center": False,
        "radio_center_marker": "x",
        "radio_center_size": 50,
        "radio_center_linewidth": 1.8,
        "label_radio_center": False,
        "band_colors_dict": {
            "149.0MHz": ("dodgerblue", "navy"),
            "164.0MHz": ("orange", "darkorange"),
            "190.0MHz": ("crimson", "darkred"),
            "205.0MHz": ("mediumorchid", "purple"),
            "223.0MHz": ("gold", "goldenrod"),
            "238.0MHz": ("teal", "darkslategray"),
        },
    },
    "spectrogram": {
        "enabled": False,
        "file_paths": USER_CONFIG["spectrogram"]["file_paths"],
        "file_path": USER_CONFIG["spectrogram"]["file_path"],
        "time_display_mode": USER_CONFIG["spectrogram"]["time_display_mode"],
        "time_start": USER_CONFIG["spectrogram"]["time_start"],
        "time_end": USER_CONFIG["spectrogram"]["time_end"],
        "f_start": USER_CONFIG["spectrogram"]["f_start"],
        "f_end": USER_CONFIG["spectrogram"]["f_end"],
        "polarization": USER_CONFIG["spectrogram"]["polarization"],
        "vmin": USER_CONFIG["spectrogram"]["vmin"],
        "vmax": USER_CONFIG["spectrogram"]["vmax"],
        "use_log10": USER_CONFIG["spectrogram"]["use_log10"],
        "cmap": USER_CONFIG["spectrogram"]["cmap"],
        "draw_colorbar": True,
        "panel_height_ratio": 0.34,
    },
    "animation": {
        "make_animation": False,
        "animation_fps": 10,
        "animation_name": "aia_raw_radio_spectrogram.mp4",
        "animation_quality": "high",
    },
    "output": {
        "output_dir": "outputs/radio/2025-05-03/AIA_Raw_Radio_Overlay",
        "save_figure": True,
        "dpi": 300,
    },
    "runtime": {
        "debug_mode": True,
        "save_individual_pols": False,
    },
}

AIA_RAW_RADIO_SPECTROGRAM_CONFIG = {
    **AIA_RADIO_HMI_CONFIG,
    "paths": {
        **AIA_RADIO_HMI_CONFIG["paths"],
        "output_dir": "outputs/radio/2025-05-03/AIA_Raw_Radio_Spectrogram",
    },
    "radio": {
        **AIA_RADIO_HMI_CONFIG["radio"],
        "radio_overlay_mode": "raw",
        "use_radec_maps": False,
    },
    "wcs_reproject": {
        **AIA_RADIO_HMI_CONFIG["wcs_reproject"],
        "use_radec_maps": False,
    },
    "gaussian": {
        **AIA_RADIO_HMI_CONFIG["gaussian"],
        "enable_gaussian_overlay": False,
        "save_gaussian_diagnostics": False,
    },
    "display": {
        **AIA_RADIO_HMI_CONFIG["display"],
        "show_radio_contours": True,
        "mark_radio_center": False,
    },
    "spectrogram": {
        **AIA_RADIO_HMI_CONFIG["spectrogram"],
        "enabled": True,
    },
    "animation": {
        **AIA_RADIO_HMI_CONFIG["animation"],
        "make_animation": True,
    },
    "output": {
        **AIA_RADIO_HMI_CONFIG["output"],
        "output_dir": "outputs/radio/2025-05-03/AIA_Raw_Radio_Spectrogram",
    },
}

AIA_MULTI_WAVE_RAW_RADIO_SPECTROGRAM_CONFIG = {
    **AIA_RADIO_HMI_CONFIG,
    "paths": {
        **AIA_RADIO_HMI_CONFIG["paths"],
        "aia_panel_base_dir_template": "data/aia/2025-05-03/{wave}",
        "output_dir": "outputs/radio/2025-05-03",
    },
    "aia": {
        **AIA_RADIO_HMI_CONFIG["aia"],
        "aia_panel_wavelengths": [94, 131, 171, 193, 211, 304],
        "aia_time_threshold_seconds": 12.0,
        "aia_panel_layout_style": "mosaic",
        "aia_panel_base_width": 4.9,
        "aia_panel_wspace": 0.0,
        "aia_panel_hspace": 0.0,
        "aia_panel_spectrogram_gap": 0.85,
        "aia_panel_show_per_panel_titles": False,
        "aia_panel_show_axis_labels": False,
        "aia_panel_show_tick_labels": True,
        "aia_panel_global_axis_labels": False,
        "aia_panel_show_grid": True,
        "aia_panel_label_mode": "inside",
        "aia_panel_label_fontsize": 8.5,
        "aia_panel_save_tight": False,
    },
    "hmi": {
        **AIA_RADIO_HMI_CONFIG["hmi"],
        "overlay_hmi": True,
    },
    "radio": {
        **AIA_RADIO_HMI_CONFIG["radio"],
        "radio_overlay_mode": "raw",
        "enable_gaussian_overlay": False,
        "use_radec_maps": False,
        "radio_start_idx": USER_CONFIG["data"]["start_idx"],
        "radio_end_idx": USER_CONFIG["data"]["end_idx"],
        "multi_band_time_tolerance_seconds": USER_CONFIG["data"][
            "multi_band_time_tolerance_seconds"
        ],
    },
    "wcs_reproject": {
        **AIA_RADIO_HMI_CONFIG["wcs_reproject"],
        "use_radec_maps": False,
    },
    "gaussian": {
        **AIA_RADIO_HMI_CONFIG["gaussian"],
        "enable_gaussian_overlay": False,
        "save_gaussian_diagnostics": False,
    },
    "display": {
        **AIA_RADIO_HMI_CONFIG["display"],
        "show_radio_contours": True,
        "contour_smooth_sigma": 1.5,
        "mark_radio_center": False,
    },
    "spectrogram": {
        **AIA_RADIO_HMI_CONFIG["spectrogram"],
        "enabled": True,
        "panel_height_ratio": 0.55,
        "hspace": 0.04,
    },
    "animation": {
        **AIA_RADIO_HMI_CONFIG["animation"],
        "animation_name": "aia_6band_hmi_raw_radio_spectrogram.mp4",
    },
    "output": {
        **AIA_RADIO_HMI_CONFIG["output"],
        "output_dir": "outputs/radio/2025-05-03",
    },
}

NEWKIRK_CONFIG = {
    "enabled": True,
    "multipliers": [1, 2, 4],
    "harmonics": [1, 2],
    "solar_radius_arcsec": 959.63,
    "output_csv": OUTPUT_CONFIG["newkirk_csv"],
    "drift_speed_csv": OUTPUT_CONFIG["drift_speed_csv"],
}

NEWKIRK_HEIGHT_COMPARISON_CONFIG = {
    "enable": True,
    "selected_models": [
        {"multiplier": 1.0, "harmonic": 1},
        {"multiplier": 1.0, "harmonic": 2},
        {"multiplier": 2.0, "harmonic": 1},
        {"multiplier": 2.0, "harmonic": 2},
        {"multiplier": 4.0, "harmonic": 1},
        {"multiplier": 4.0, "harmonic": 2},
    ],
    "solar_radius_arcsec": None,
    "plot_height_frequency": True,
    "plot_height_time": True,
    "plot_residual_frequency": True,
    "output_table_name": "gaussian_newkirk_height_comparison_table.csv",
    "raw_output_table_name": "gaussian_newkirk_height_rows.csv",
    "height_frequency_plot_name": "newkirk_height_frequency",
    "height_time_plot_name": "newkirk_height_time",
    "height_residual_plot_name": "newkirk_height_residual_frequency",
    "height_residual_summary_name": "gaussian_newkirk_height_residual_summary.csv",
    "reverse_frequency_axis": False,
    "color_by": "source_type",
    "drift_time_tolerance_s": 0.75,
    "drift_frequency_tolerance_mhz": "adaptive_half_band_spacing",
    "max_adaptive_frequency_tolerance_mhz": 15.0,
    "min_adaptive_frequency_tolerance_mhz": 5.0,
}

DRIFT_SELECTION_PRODUCT_CONFIG = {
    "enable": True,
    "save_raw_preview": True,
    "save_annotated_preview": True,
    "save_selection_csv": True,
    "save_metadata_json": True,
    "save_per_drift_cutouts": True,
    "cutout_time_padding_s": 2.0,
    "cutout_frequency_padding_mhz": 20.0,
    "annotate_drift_rate": True,
    "annotate_endpoints": True,
    "preserve_existing": True,
    "dpi": 200,
    "output_subdir": OUTPUT_CONFIG["drift_selection_subdir"],
}

RADIO_DIAGNOSTIC_PRESENTATION_CONFIG = {
    "enable": True,
    "enable_static_summary": OUTPUT_CONFIG["enable_static_summary"],
    "enable_html_dashboard": OUTPUT_CONFIG["enable_html_dashboard"],
    "enable_debug_center_facets": False,
    "enable_debug_height_time_facets": False,
    "enable_debug_drift_band_matching": False,
    "enable_debug_trajectory_by_frequency": False,
    "enable_event_height_comparison": True,
    "enable_event_speed_frequency": True,
    "comparison_frequency_mhz": [149, 164, 190, 205, 223, 238],
    "drift_source_type_map": {
        "drift_001": "typeIII",
        "drift_002": "typeIII",
        "drift_003": "spike",
        "drift_004": "spike",
    },
    "drift_time_tolerance_s": 0.75,
    "drift_frequency_tolerance_mhz": "adaptive_half_band_spacing",
    "max_adaptive_frequency_tolerance_mhz": 15.0,
    "min_adaptive_frequency_tolerance_mhz": 5.0,
    "selected_newkirk_multiplier": 2.0,
    "selected_newkirk_harmonic": 2,
    "reference_newkirk_assumption": "2xH2",
    "connect_same_drift_only": False,
    "reverse_frequency_axis": False,
    "best_model_metric": "median_abs_residual_rsun",
    "top_residual_models": 3,
    "summary_panel_name": "newkirk_frequency_priority_summary",
    "center_facets_name": "source_center_frequency_facets",
    "trajectory_by_frequency_name_template": "source_trajectory",
    "drift_band_matching_name": "drift_frequency_band_matching",
    "height_time_facets_name": "height_time_frequency_facets",
    "event_height_comparison_name": "newkirk_height_comparison",
    "event_speed_frequency_name": "newkirk_speed_frequency_scatter",
    "selected_band_newkirk_table_name": "event_selected_band_newkirk_table.csv",
    "physical_consistency_report_name": "newkirk_physical_consistency_report.md",
    "dashboard_name": "radio_newkirk_frequency_priority_dashboard.html",
    "summary_csv_name": "radio_newkirk_frequency_priority_summary.csv",
}

EVENT_CONFIG = apply_event_path_overrides(
    {
        "user": USER_CONFIG,
        "output": OUTPUT_CONFIG,
        "aia_radio_hmi": AIA_RADIO_HMI_CONFIG,
        "aia_raw_radio_spectrogram": AIA_RAW_RADIO_SPECTROGRAM_CONFIG,
        "aia_multi_wave_raw_radio_spectrogram": AIA_MULTI_WAVE_RAW_RADIO_SPECTROGRAM_CONFIG,
        "newkirk": NEWKIRK_CONFIG,
        "newkirk_height_comparison": NEWKIRK_HEIGHT_COMPARISON_CONFIG,
        "drift_selection_products": DRIFT_SELECTION_PRODUCT_CONFIG,
        "diagnostic_presentation": RADIO_DIAGNOSTIC_PRESENTATION_CONFIG,
    },
    "radio_20250503_config",
)

USER_CONFIG = EVENT_CONFIG["user"]
OUTPUT_CONFIG = EVENT_CONFIG["output"]
AIA_RADIO_HMI_CONFIG = EVENT_CONFIG["aia_radio_hmi"]
AIA_RAW_RADIO_SPECTROGRAM_CONFIG = EVENT_CONFIG["aia_raw_radio_spectrogram"]
AIA_MULTI_WAVE_RAW_RADIO_SPECTROGRAM_CONFIG = EVENT_CONFIG[
    "aia_multi_wave_raw_radio_spectrogram"
]
NEWKIRK_CONFIG = EVENT_CONFIG["newkirk"]
NEWKIRK_HEIGHT_COMPARISON_CONFIG = EVENT_CONFIG["newkirk_height_comparison"]
DRIFT_SELECTION_PRODUCT_CONFIG = EVENT_CONFIG["drift_selection_products"]
RADIO_DIAGNOSTIC_PRESENTATION_CONFIG = EVENT_CONFIG["diagnostic_presentation"]
