name: solar_simulation
channels:
  - conda-forge
dependencies:
  - python=3.14
  - numpy
  - scipy
  - matplotlib
  - pillow
  - pyvista
  - vtk
  - h5py
  - imageio
  - imageio-ffmpeg
  - ffmpeg
  - pytest
  - ruff
  - openmpi
