# SPDX-License-Identifier: GPL-3.0-only
"""Authoritative atomic-function catalog and ten native page templates."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from .flows import AppV1FlowV1, FlowEdgeV1, FlowNodeV1, FunctionCatalog
from .function_specs import (
    ArtifactPortSpec,
    FunctionSpec,
    ParameterSpec,
    ScientificVariantSpec,
    VariantFamilySpec,
)
from .radio_catalog_adapter import radio_workspace_functions


def _p(
    parameter_id: str,
    label: str,
    kind: str = "string",
    *,
    default: Any = None,
    required: bool = False,
    advanced: bool = False,
    flag: str | None = None,
    aliases: tuple[str, ...] = (),
    negative: str | None = None,
    positional: bool = False,
    choices: tuple[Any, ...] = (),
    minimum: float | None = None,
    maximum: float | None = None,
    unit: str = "",
    help_text: str = "",
    config_path: str | None = None,
    extensions: tuple[str, ...] = (),
    list_style: str = "comma",
    conflicts: tuple[str, ...] = (),
    requires: tuple[str, ...] = (),
    item_kind: str | None = None,
) -> ParameterSpec:
    return ParameterSpec(
        parameter_id=parameter_id,
        label=label,
        kind=kind,  # type: ignore[arg-type]
        default=default,
        required=required,
        group="advanced" if advanced else "common",
        cli_flag=flag,
        cli_aliases=aliases,
        negative_cli_flag=negative,
        positional=positional,
        choices=choices,
        minimum=minimum,
        maximum=maximum,
        unit=unit,
        help_text=help_text,
        config_path=config_path,
        path_extensions=extensions,
        conflicts_with=conflicts,
        requires=requires,
        allow_empty=not required,
        item_kind=item_kind,
        list_style=list_style,  # type: ignore[arg-type]
    )


def _in(
    port_id: str,
    label: str,
    *types: str,
    required: bool = False,
    parameter_id: str | None = None,
) -> ArtifactPortSpec:
    return ArtifactPortSpec(
        port_id,
        label,
        tuple(types),
        required=required,
        parameter_id=parameter_id,
    )


def _out(port_id: str, label: str, *types: str, multiple: bool = False) -> ArtifactPortSpec:
    return ArtifactPortSpec(
        port_id,
        label,
        tuple(types),
        required=False,
        multiple=multiple,
    )


OUTPUT_DIR = _p(
    "output_dir",
    "Output folder",
    "directory",
    flag="--output-dir",
    advanced=True,
    help_text="Optional folder below an allowed output root.",
)

FUNCTIONS: tuple[FunctionSpec, ...] = (
    FunctionSpec(
        "artifact-input",
        "Existing Artifact",
        "Data",
        "Use an explicitly selected prior artifact as a typed workflow input.",
        "solar_apps.frontends.app_v1.flow_builtin_worker",
        parameters=(
            _p("path", "Artifact", "file", required=True, flag="--path"),
            _p(
                "artifact_type",
                "Artifact type",
                "enum",
                default="image",
                flag="--artifact-type",
                choices=(
                    "image",
                    "table",
                    "roi",
                    "time-series",
                    "spectrum",
                    "media",
                    "manifest",
                    "radio-fits",
                    "aia-fits",
                ),
            ),
        ),
        outputs=(_out("artifact", "Artifact", "*"),),
        fixed_arguments=("--operation", "artifact-input"),
        allowed_roots_flag="--allowed-roots",
        page_templates=("workbench", "radio-workspace"),
    ),
    FunctionSpec(
        "image-discover",
        "Discover Image Sequence",
        "Data",
        "Discover a local image sequence without opening a browser.",
        "solar_apps.frontends.app_v1.flow_builtin_worker",
        parameters=(
            _p("input_dir", "Image folder", "directory", required=True, flag="--input-dir"),
            _p(
                "recursive",
                "Recursive",
                "boolean",
                default=False,
                flag="--recursive",
                negative="--no-recursive",
            ),
            _p(
                "extensions",
                "Extensions",
                "list",
                default=[".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tif", ".tiff"],
                flag="--extensions",
            ),
        ),
        outputs=(_out("images", "Images", "image", multiple=True),),
        fixed_arguments=("--operation", "image-discover"),
        allowed_roots_flag="--allowed-roots",
        page_templates=("image-viewer",),
    ),
    FunctionSpec(
        "aia-process",
        "AIA Processing",
        "Imaging & Localization",
        "Process AIA frames, mosaics, and difference products.",
        "solar_apps.workflows.aia.application",
        parameters=(
            _p("root_dir", "Observation root", "directory", flag="--root"),
            _p("year", "Year", flag="--year"),
            _p("date", "Observation date", flag="--date"),
            _p("data_path", "AIA folder", "directory", flag="--data-path"),
            OUTPUT_DIR,
            _p(
                "mode",
                "Mode",
                "enum",
                flag="--mode",
                choices=("test", "single", "mosaic"),
            ),
            _p("test_file", "Test FITS", "file", flag="--test-file", extensions=(".fits", ".fit", ".fts")),
            _p("test_wave", "Test wavelength", "integer", flag="--test-wave", minimum=1),
            _p("test_index", "Test index", "integer", flag="--test-index", minimum=0),
            _p("use_test_mode", "Use test mode", "boolean", flag="--use-test-mode"),
            _p(
                "waves",
                "Wavelengths",
                "list",
                flag="--waves",
                list_style="repeat",
            ),
            _p("start", "Start index", "integer", flag="--start", minimum=0),
            _p("end", "End index", "integer", flag="--end", minimum=0),
            _p("roi", "ROI bounds", "list", flag="--roi", list_style="repeat"),
            _p("dpi", "DPI", "integer", flag="--dpi", minimum=36, maximum=2400),
            _p("workers", "Workers", "integer", flag="--workers", minimum=1, maximum=64, advanced=True),
            _p("mosaic_ncols", "Mosaic columns", "integer", flag="--mosaic-ncols", minimum=1, advanced=True),
            _p("mosaic_manual_layout", "Manual mosaic layout", "boolean", flag="--mosaic-manual-layout", negative="--no-mosaic-manual-layout", advanced=True),
            _p("mosaic_seamless", "Seamless mosaic", "boolean", flag="--mosaic-seamless", negative="--no-mosaic-seamless", advanced=True),
            _p("mosaic_show_outer_axes", "Show mosaic outer axes", "boolean", flag="--mosaic-show-outer-axes", negative="--no-mosaic-outer-axes", advanced=True),
            _p("mosaic_ticklabel_fontsize", "Mosaic tick-label size", "integer", flag="--mosaic-ticklabel-fontsize", minimum=1, advanced=True),
            _p("mosaic_axislabel_fontsize", "Mosaic axis-label size", "integer", flag="--mosaic-axislabel-fontsize", minimum=1, advanced=True),
            _p("mosaic_save_tight", "Tight mosaic output", "boolean", flag="--mosaic-save-tight", negative="--no-mosaic-save-tight", advanced=True),
            _p("mosaic_max_workers", "Mosaic workers", "integer", flag="--mosaic-max-workers", minimum=1, maximum=64, advanced=True),
            _p("mosaic_max_slots", "Mosaic slots", "integer", flag="--mosaic-max-slots", minimum=1, advanced=True),
            _p("mosaic_difference_output_subdir", "Mosaic difference subfolder", flag="--mosaic-difference-output-subdir", advanced=True),
            _p("mosaic_original_plus_difference_output_subdir", "Original + difference subfolder", flag="--mosaic-original-plus-difference-output-subdir", advanced=True),
            _p("mosaic_left", "Mosaic left margin", "number", flag="--mosaic-left", advanced=True),
            _p("mosaic_right", "Mosaic right margin", "number", flag="--mosaic-right", advanced=True),
            _p("mosaic_bottom", "Mosaic bottom margin", "number", flag="--mosaic-bottom", advanced=True),
            _p("mosaic_top", "Mosaic top margin", "number", flag="--mosaic-top", advanced=True),
            _p("mosaic_force_fill_axes", "Fill mosaic axes", "boolean", flag="--mosaic-force-fill-axes", negative="--no-mosaic-force-fill-axes", advanced=True),
            _p("mosaic_debug_layout", "Debug mosaic layout", "boolean", flag="--mosaic-debug-layout", advanced=True),
            _p("mosaic_reduce_tick_overlap", "Reduce tick overlap", "boolean", flag="--mosaic-reduce-tick-overlap", negative="--no-mosaic-reduce-tick-overlap", advanced=True),
            _p("mosaic_max_ticks_per_axis", "Maximum ticks per axis", "integer", flag="--mosaic-max-ticks-per-axis", minimum=1, advanced=True),
            _p("mosaic_hide_boundary_ticklabels", "Hide boundary tick labels", "boolean", flag="--mosaic-hide-boundary-ticklabels", negative="--no-mosaic-hide-boundary-ticklabels", advanced=True),
            _p("mosaic_x_tick_strategy", "Mosaic X tick strategy", "enum", flag="--mosaic-x-tick-strategy", choices=("all_bottom", "first_bottom_only", "alternating_bottom"), advanced=True),
            _p("mosaic_y_tick_strategy", "Mosaic Y tick strategy", "enum", flag="--mosaic-y-tick-strategy", choices=("all_left", "first_left_only", "alternating_left"), advanced=True),
            _p("mosaic_outer_axislabel_once", "One outer axis label", "boolean", flag="--mosaic-outer-axislabel-once", negative="--no-mosaic-outer-axislabel-once", advanced=True),
            _p("mosaic_global_outer_axes", "Global mosaic outer axes", "boolean", flag="--mosaic-global-outer-axes", negative="--no-mosaic-global-outer-axes", advanced=True),
            _p("vmin", "Display minimum", "number", flag="--vmin", advanced=True),
            _p("vmax", "Display maximum", "number", flag="--vmax", advanced=True),
            _p("cmap", "Color map", flag="--cmap", advanced=True),
            _p("show_grid", "Show grid", "boolean", flag="--show-grid", negative="--no-grid", advanced=True),
            _p("show_limb", "Show limb", "boolean", flag="--show-limb", advanced=True),
            _p("colorbar", "Color bar", "boolean", flag="--colorbar", advanced=True),
            _p("also_save_single", "Also save single panels", "boolean", flag="--also-save-single", advanced=True),
            _p("draw_original", "Draw original", "boolean", flag="--draw-original", negative="--no-draw-original", advanced=True),
            _p("mosaic_difference_inline", "Inline mosaic difference", "boolean", flag="--mosaic-difference-inline", negative="--no-mosaic-difference-inline", advanced=True),
            _p("draw_difference", "Draw difference", "boolean", flag="--draw-difference", negative="--no-draw-difference", advanced=True),
            _p("difference_method", "Difference method", "enum", flag="--difference-method", choices=("base", "running"), advanced=True),
            _p("difference_output_mode", "Difference output", "enum", flag="--difference-output-mode", choices=("auto", "mosaic", "single", "both"), advanced=True),
            _p("difference_wavelengths", "Difference wavelengths", "list", flag="--diff-waves", aliases=("--difference-wavelengths",), list_style="repeat", advanced=True),
            _p("difference_base_index", "Difference base index", "integer", flag="--diff-base-index", minimum=0, advanced=True),
            _p("difference_norm_mode", "Difference normalization", "enum", flag="--difference-norm-mode", choices=("auto", "fixed", "config"), advanced=True),
            _p("difference_percentile", "Difference percentile", "number", flag="--difference-percentile", minimum=0, maximum=100, advanced=True),
            _p("difference_vmin", "Difference minimum", "number", flag="--difference-vmin", advanced=True),
            _p("difference_vmax", "Difference maximum", "number", flag="--difference-vmax", advanced=True),
            _p("difference_vmin_by_wave", "Difference minima by wavelength", "list", flag="--difference-vmin-by-wave", list_style="repeat", advanced=True),
            _p("difference_vmax_by_wave", "Difference maxima by wavelength", "list", flag="--difference-vmax-by-wave", list_style="repeat", advanced=True),
            _p("difference_vlim_by_wave", "Symmetric limits by wavelength", "list", flag="--difference-vlim-by-wave", list_style="repeat", advanced=True),
            _p("difference_cmap", "Difference color map", flag="--difference-cmap", advanced=True),
            _p("difference_cmap_mode", "Difference color-map mode", "enum", flag="--difference-cmap-mode", choices=("band", "diverging", "custom"), advanced=True),
            _p("warn_band_difference_cmap", "Warn for band difference map", "boolean", flag="--warn-band-difference-cmap", advanced=True),
            _p("difference_save_reference", "Save difference reference", "boolean", flag="--difference-save-reference", negative="--no-difference-save-reference", advanced=True),
            _p("difference_show_colorbar", "Difference color bar", "boolean", flag="--difference-colorbar", negative="--no-difference-colorbar", advanced=True),
            _p("difference_derotate", "Derotate difference frames", "boolean", flag="--difference-derotate", negative="--no-difference-derotate", advanced=True),
        ),
        outputs=(
            _out("images", "AIA images", "image", multiple=True),
            _out("manifest", "Manifest", "manifest"),
        ),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("image-viewer",),
    ),
    FunctionSpec(
        "hmi-overlay",
        "AIA/HMI Overlay",
        "Context",
        "Overlay HMI contours on matched AIA context images.",
        "solar_apps.workflows.hmi.overlay_cli",
        parameters=(
            _p("input_dir_aia", "AIA folder", "directory", required=True, flag="--input-dir-aia"),
            _p("input_dir_hmi", "HMI folder", "directory", required=True, flag="--input-dir-hmi"),
            _p("roi_bounds", "ROI bounds", flag="--roi-bounds"),
            _p("threshold_gauss", "Threshold", "number", flag="--threshold-gauss", unit="G"),
            _p("gaussian_sigma", "Gaussian sigma", "number", flag="--gaussian-sigma", minimum=0),
            _p("vmin", "Display minimum", "number", flag="--vmin", advanced=True),
            _p("vmax", "Display maximum", "number", flag="--vmax", advanced=True),
            _p("contour_level_gauss", "Contour level", "number", flag="--contour-level-gauss", unit="G"),
            _p("max_time_diff_seconds", "Time tolerance", "number", default=24.0, flag="--max-time-diff-seconds", minimum=0, unit="s"),
            _p("dpi", "DPI", "integer", default=300, flag="--dpi", minimum=72, maximum=1200),
            _p("show_plot", "Show worker plot", "boolean", default=False, flag="--show-plot", advanced=True),
            _p("show_progress", "Show progress", "boolean", default=True, flag="--show-progress", advanced=True),
            OUTPUT_DIR,
        ),
        outputs=(_out("images", "Overlay images", "image", multiple=True),),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("image-viewer",),
    ),
    FunctionSpec(
        "source-map-render",
        "Source Map Render",
        "Imaging & Localization",
        "Discover and render single- or multi-frequency radio source maps.",
        "solar_apps.frontends.app_v1.source_map_flow_worker",
        parameters=(
            _p("config", "Event config", default="solar_apps.workflows.radio.configs.radio_20250124_config", flag="--config"),
            _p("source_path", "Radio source", "directory", required=True, flag="--source-path"),
            _p("mode", "Map mode", "enum", default="single_band", flag="--mode", choices=("single_band", "multi_band")),
            _p("frequencies", "Frequencies", "list", default=[149, 164, 190], flag="--frequencies", unit="MHz"),
            _p("polarization", "Polarization", "enum", default="RR+LL", flag="--polarization", choices=("RR+LL", "RR", "LL")),
            _p("cmap", "Color map", default="hot", flag="--cmap"),
            _p("color_range_mode", "Color range", "enum", default="auto", flag="--color-range-mode", choices=("auto", "fixed", "global")),
            _p("fixed_vmin", "Fixed minimum", "number", flag="--fixed-vmin", advanced=True, requires=("fixed_vmax",)),
            _p("fixed_vmax", "Fixed maximum", "number", flag="--fixed-vmax", advanced=True, requires=("fixed_vmin",)),
            _p("gaussian_overlay", "Gaussian overlay", "boolean", default=False, flag="--gaussian-overlay"),
            _p("spectrogram_panel", "Spectrogram panel", "boolean", default=False, flag="--spectrogram-panel"),
            _p("background_mode", "Background", "enum", default="off", flag="--background-mode", choices=("off", "noise_map_only", "local_mesh", "local_median"), advanced=True),
            _p("background_display", "Background for display", "boolean", default=False, flag="--background-display", advanced=True),
            _p("background_fit", "Background for fit", "boolean", default=False, flag="--background-fit", advanced=True),
            OUTPUT_DIR,
        ),
        outputs=(
            _out("images", "Source maps", "image", multiple=True),
            _out("metadata", "Source-map metadata", "manifest", multiple=True),
        ),
        output_flag="--output-dir",
        output_parameter="output_dir",
        allowed_roots_flag="--allowed-roots",
        page_templates=("source-map", "radio-composite"),
        aliases=("inspect-source-map",),
    ),
    FunctionSpec(
        "gaussian-fit",
        "Gaussian Source Fit",
        "Imaging & Localization",
        "Fit one or more Gaussian radio sources without changing map rendering.",
        "solar_apps.workflows.radio.source_map_cli",
        parameters=(
            _p("config", "Event config", default="solar_apps.workflows.radio.configs.radio_20250124_config", flag="--config"),
            _p("single_file_path", "Radio FITS", "file", required=True, config_path="data.single_file_path", extensions=(".fits", ".fit", ".fts")),
            _p("source_count", "Source count", "integer", default=1, minimum=1, maximum=3, config_path="gaussian.multi_gaussian_source_count"),
            _p("polarization", "Polarization", "enum", default="RR", choices=("RR", "LL", "RR+LL"), config_path="data.polarization"),
            _p("save_diagnostics", "Save diagnostics", "boolean", default=True, config_path="features.save_gaussian_diagnostics"),
            OUTPUT_DIR,
        ),
        outputs=(
            _out("centers", "Gaussian centers", "table"),
            _out("diagnostics", "Diagnostics", "image", multiple=True),
        ),
        config_json_flag="--workspace-config-json",
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("source-map",),
        aliases=("fit-gaussian",),
    ),
    FunctionSpec(
        "bad-frame-discover",
        "Bad Frame Review Discovery",
        "Data",
        "Discover frequency bands and candidates for native frame review.",
        "solar_apps.frontends.app_v1.native_science_worker",
        parameters=(
            _p("input_dir", "Radio root", "directory", required=True, flag="--input-dir"),
            OUTPUT_DIR,
        ),
        outputs=(_out("review", "Review discovery", "manifest"),),
        fixed_arguments=("bad-frame-discover", "--module-id", "bad-frame-review"),
        output_flag="--output-dir",
        output_parameter="output_dir",
        allowed_roots_flag="--allowed-root",
        repeat_allowed_roots=True,
        page_templates=("bad-frame-review",),
    ),
    FunctionSpec(
        "center-extraction",
        "Threshold Center Extraction",
        "Imaging & Localization",
        "Extract radio-source centers from a threshold mask.",
        "solar_apps.workflows.radio.centers_application",
        parameters=(
            _p("radio_dir", "Radio folder", "directory", required=True, flag="--radio-dir"),
            _p("output_file", "Center table", "file", flag="--out", extensions=(".csv", ".xlsx", ".xls")),
            _p("pattern", "File pattern", default="*.fits", flag="--pattern"),
            _p("recursive", "Recursive", "boolean", default=False, flag="--recursive"),
            _p("freqs", "Frequencies", "list", flag="--freqs", unit="MHz"),
            _p("polarizations", "Polarizations", "list", flag="--polarizations"),
            _p("time_start", "Start time", "time", flag="--time-start"),
            _p("time_end", "End time", "time", flag="--time-end"),
            _p("threshold", "Threshold fraction", "number", default=0.95, flag="--threshold", minimum=0, maximum=1),
            _p("threshold_mode", "Threshold mode", "enum", default="bg_peak", flag="--threshold-mode", choices=("peak", "bg_peak", "percentile")),
            _p("background_percentile", "Background percentile", "number", default=5.0, flag="--background-percentile", minimum=0, maximum=100),
            _p("component", "Mask component", "enum", default="peak", flag="--component", choices=("peak", "largest", "brightest")),
            _p("use_abs", "Use absolute values", "boolean", default=False, flag="--use-abs"),
            _p("min_pixels", "Minimum pixels", "integer", default=1, flag="--min-pixels", minimum=1),
            _p("default_pol", "Fallback polarization", "enum", default="L+R", flag="--default-pol", choices=("LCP", "RCP", "L+R", "unknown")),
            _p("make_sum", "Create L+R centers", "boolean", default=False, flag="--make-sum"),
            _p("pair_time_tolerance_sec", "Pair tolerance", "number", default=0.5, flag="--pair-time-tolerance-sec", minimum=0, unit="s"),
        ),
        outputs=(_out("centers", "Center table", "table"),),
        output_flag="--out",
        output_parameter="output_file",
        default_output_name="radio_centers.csv",
        variant_family=VariantFamilySpec(
            "centroid-method",
            "Centroid method",
            (
                "Weighted centroid uses intensities inside the accepted mask; "
                "geometric centroid weights every accepted pixel equally and can "
                "change the reported source position."
            ),
            (
                ScientificVariantSpec(
                    "weighted",
                    "Intensity-weighted centroid",
                    "Primary center estimate weighted by masked image intensity.",
                    "solar_apps.workflows.radio.centers_application",
                    ("--centroid", "weighted"),
                    is_primary=True,
                    compatibility="native canonical",
                    test_status="verified",
                ),
                ScientificVariantSpec(
                    "geometric",
                    "Geometric mask centroid",
                    "Advanced center estimate using equal weight for mask pixels.",
                    "solar_apps.workflows.radio.centers_application",
                    ("--centroid", "geometric"),
                    compatibility="native advanced",
                    test_status="verified",
                ),
            ),
        ),
        aliases=("extract-centers",),
        page_templates=("source-map", "source-trajectory"),
    ),
    FunctionSpec(
        "roi-lightcurve",
        "ROI Light Curve",
        "ROI & Time Series",
        "Measure a selected HPLN/HPLT ROI across radio FITS frames.",
        "solar_apps.frontends.radio.roi_lightcurve.roi_lightcurve_application",
        parameters=(
            _p("radio_dir", "Radio folder", "directory", required=True, flag="--radio-dir"),
            _p("pattern", "File pattern", default="*.fits", flag="--pattern", advanced=True),
            _p("recursive", "Recursive", "boolean", default=True, flag="--recursive", negative="--no-recursive"),
            _p("freqs", "Frequencies", "list", flag="--freqs", unit="MHz"),
            _p("polarization", "Polarization", "enum", default="L+R", flag="--polarization", choices=("L+R", "LCP", "RCP", "all")),
            _p("time_start", "Start time", "time", flag="--time-start"),
            _p("time_end", "End time", "time", flag="--time-end"),
            _p("pair_time_tolerance_sec", "Pair tolerance", "number", default=1.0, flag="--pair-time-tolerance-sec", minimum=0, unit="s", advanced=True),
            _p("roi_bounds", "ROI bounds", default="-300,-300,300,300", flag="--roi-bounds", conflicts=("roi_json",)),
            _p("roi_json", "ROI JSON", "file", flag="--roi-json", extensions=(".json",), conflicts=("roi_bounds",)),
            _p("metric", "Metric", "enum", default="raw_sum", flag="--metric", choices=("raw_sum", "raw_mean", "raw_peak")),
            _p("selected_products", "Products", "list", default=["csv", "json", "reference_png", "lightcurve_png"], flag="--selected-products", advanced=True),
            _p("detail_frequency_mhz", "Detail frequency", "number", flag="--detail-frequency-mhz", unit="MHz", advanced=True),
            _p("plot_style", "Plot style", "enum", default="scatter", flag="--plot-style", choices=("scatter", "line"), advanced=True),
            _p("y_transform", "Y transform", "enum", default="linear", flag="--y-transform", choices=("linear", "log10"), advanced=True),
            _p("overwrite", "Overwrite", "boolean", default=False, flag="--overwrite", advanced=True),
            _p("output_dir", "Output folder", "directory", flag="--out-dir", advanced=True),
        ),
        inputs=(_in("roi", "ROI", "roi", parameter_id="roi_json"),),
        outputs=(
            _out("curve", "Light curve", "time-series", "table"),
            _out("plots", "Plots", "image", multiple=True),
            _out("roi", "ROI", "roi"),
        ),
        output_flag="--out-dir",
        output_parameter="output_dir",
        page_templates=("roi-lightcurve",),
        aliases=("extract-light-curves",),
    ),
    FunctionSpec(
        "dart-spectrum",
        "DART Spectrum",
        "Spectrum & Physics",
        "Render bounded DART dynamic spectra and narrow-band curves.",
        "solar_apps.frontends.app_v1.native_science_worker",
        parameters=(
            _p("input_dir", "DART folder", "directory", required=True, flag="--input-dir"),
            _p("center_frequencies", "Center frequencies", "list", default=[149, 164, 190], flag="--center-frequencies", unit="MHz"),
            _p("bandwidth_mhz", "Bandwidth", "number", default=2.0, flag="--bandwidth-mhz", minimum=0.001, unit="MHz"),
            _p("display_mode", "Display", "enum", default="db", flag="--display-mode", choices=("db", "linear")),
            _p("max_frequency_samples", "Frequency samples", "integer", default=1200, flag="--max-frequency-samples", minimum=32, advanced=True),
            _p("max_time_samples", "Time samples", "integer", default=1200, flag="--max-time-samples", minimum=32, advanced=True),
            _p("chunk_memory_mb", "Chunk memory", "integer", default=128, flag="--chunk-memory-mb", minimum=1, unit="MiB", advanced=True),
            _p("dpi", "DPI", "integer", default=150, flag="--dpi", minimum=72, maximum=600, advanced=True),
            OUTPUT_DIR,
        ),
        outputs=(
            _out("spectrum", "Dynamic spectrum", "spectrum", "image"),
            _out("curves", "Narrow-band curves", "time-series", "image"),
        ),
        fixed_arguments=("dart-render", "--module-id", "dart-spectrogram"),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("dart-spectrogram", "radio-composite"),
    ),
    FunctionSpec(
        "drift-rate",
        "Drift Rate",
        "Spectrum & Physics",
        "Persist an explicitly selected two-point drift measurement.",
        "solar_apps.workflows.radio.drift_selection_cli",
        parameters=(
            _p("drift_lines", "Drift lines", "object", required=True, flag="--drift-lines-json"),
            OUTPUT_DIR,
        ),
        inputs=(_in("spectrum", "Spectrum", "spectrum"),),
        outputs=(_out("drift", "Drift table", "table"),),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("dart-spectrogram",),
        aliases=("select-drift-lines",),
    ),
    FunctionSpec(
        "newkirk-diagnostics",
        "Newkirk Diagnostics",
        "Spectrum & Physics",
        "Calculate Newkirk diagnostics from Gaussian and/or drift tables.",
        "solar_apps.workflows.radio.physical_diagnostics_cli",
        parameters=(
            _p("gaussian_csv", "Gaussian CSV", "file", flag="--gaussian-csv", extensions=(".csv",)),
            _p("drift_csv", "Drift CSV", "file", flag="--drift-csv", extensions=(".csv",)),
            _p("config", "Event config", default="solar_apps.workflows.radio.configs.radio_20250124_config", flag="--config"),
            OUTPUT_DIR,
        ),
        inputs=(
            _in(
                "gaussian",
                "Gaussian centers",
                "table",
                parameter_id="gaussian_csv",
            ),
            _in("drift", "Drift table", "table", parameter_id="drift_csv"),
        ),
        outputs=(_out("diagnostics", "Physical diagnostics", "table", "image"),),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("dart-spectrogram",),
        aliases=("analyze-existing-tables",),
        required_any=("gaussian_csv", "drift_csv"),
    ),
    FunctionSpec(
        "radio-composite",
        "Radio Composite",
        "Context",
        "Combine source-map products and DART context into a composite package.",
        "solar_apps.frontends.app_v1.native_science_worker",
        parameters=(
            _p("input_dir", "Radio folder", "directory", required=True, flag="--input-dir"),
            _p("secondary_dir", "DART folder", "directory", required=True, flag="--secondary-dir"),
            OUTPUT_DIR,
        ),
        inputs=(
            _in("maps", "Source maps", "image", parameter_id="input_dir"),
            _in(
                "spectrum",
                "DART spectrum",
                "spectrum",
                "image",
                parameter_id="secondary_dir",
            ),
        ),
        outputs=(_out("composite", "Composite discovery", "manifest"),),
        fixed_arguments=("radio-composite-discover", "--module-id", "radio-composite"),
        output_flag="--output-dir",
        output_parameter="output_dir",
        page_templates=("radio-composite",),
    ),
    FunctionSpec(
        "trajectory-export",
        "Source Trajectory",
        "Trajectory & Media",
        "Filter and export a static radio-source trajectory with optional AIA context.",
        "solar_apps.workflows.radio.trajectory_cli",
        parameters=(
            _p("centers", "Center table", "file", required=True, flag="--centers", extensions=(".csv", ".xlsx", ".xls")),
            _p("output_file", "Output HTML", "file", flag="--out", advanced=True, extensions=(".html",)),
            _p("frame_time", "Frame time", "time", flag="--frame-time"),
            _p("frame_index", "Frame index", "integer", default=-1, flag="--frame-index"),
            _p("mode", "Frame mode", "enum", default="tail", flag="--mode", choices=("current", "tail", "all")),
            _p("tail_n", "Tail length", "integer", default=5, flag="--tail-n", minimum=1),
            _p("freqs", "Frequencies", "list", flag="--freqs", unit="MHz"),
            _p("polarizations", "Polarizations", "list", flag="--polarizations"),
            _p("center_methods", "Center methods", "list", flag="--center-methods"),
            _p("draw_lines", "Draw lines", "boolean", default=True, negative="--no-lines"),
            _p("compare_lr", "Compare L/R", "boolean", default=False, flag="--compare-lr"),
            _p("compare_tolerance_sec", "Comparison tolerance", "number", default=1.0, flag="--compare-tolerance-sec", minimum=0, unit="s", advanced=True),
            _p("aia_dir", "AIA folder", "directory", flag="--aia-dir"),
            _p("aia_pattern", "AIA pattern", default="*.fits", flag="--aia-pattern", advanced=True),
            _p("max_aia_dt_sec", "AIA tolerance", "number", default=3600.0, flag="--max-aia-dt-sec", minimum=0, unit="s", advanced=True),
            _p("aia_max_pixels", "AIA maximum pixels", "integer", default=1024, flag="--aia-max-pixels", minimum=1, advanced=True),
            _p("aia_log_scale", "AIA log scale", "boolean", default=True, negative="--aia-linear", advanced=True),
            _p("aia_wcs_mode", "AIA WCS", "enum", default="header", flag="--aia-wcs-mode", choices=("header", "sunpy"), advanced=True),
        ),
        inputs=(
            _in(
                "centers_input",
                "Centers",
                "table",
                parameter_id="centers",
            ),
        ),
        outputs=(_out("trajectory", "Trajectory", "image", "media"),),
        page_templates=("source-trajectory",),
    ),
    FunctionSpec(
        "dem-radio-overlay",
        "DEM Radio Overlay",
        "Context",
        "Overlay DEM brightness-temperature and radio context products.",
        "solar_apps.workflows.xray_dem.dem_radio_cli",
        parameters=(
            _p("aia_fits", "AIA FITS", "file", required=True, flag="--aia-fits", extensions=(".fits", ".fit", ".fts")),
            _p("tb_data", "Tb data", "file", required=True, flag="--tb-data", extensions=(".npy",)),
            _p("radio_file", "Radio FITS", "file", flag="--radio-file", extensions=(".fits", ".fit", ".fts")),
            _p("radio_dir", "Radio folder", "directory", flag="--radio-dir"),
            _p("radio_pattern", "Radio pattern", default="*.fits", flag="--radio-pattern", advanced=True),
            _p("time_match_level", "Time match level", "integer", flag="--time-match-level", advanced=True),
            _p("tb_pixel_size", "Tb pixel size", "number", flag="--tb-pixel-size", advanced=True),
            _p("tb_xmin", "Tb X minimum", "number", flag="--tb-xmin", advanced=True),
            _p("tb_xmax", "Tb X maximum", "number", flag="--tb-xmax", advanced=True),
            _p("tb_ymin", "Tb Y minimum", "number", flag="--tb-ymin", advanced=True),
            _p("tb_ymax", "Tb Y maximum", "number", flag="--tb-ymax", advanced=True),
            _p("display_mode", "Display mode", flag="--display-mode"),
            _p("display_xmin", "Display X minimum", "number", flag="--display-xmin", advanced=True),
            _p("display_xmax", "Display X maximum", "number", flag="--display-xmax", advanced=True),
            _p("display_ymin", "Display Y minimum", "number", flag="--display-ymin", advanced=True),
            _p("display_ymax", "Display Y maximum", "number", flag="--display-ymax", advanced=True),
            _p("percentile_low", "Percentile low", "number", flag="--percentile-low", minimum=0, maximum=100, advanced=True),
            _p("percentile_high", "Percentile high", "number", flag="--percentile-high", minimum=0, maximum=100, advanced=True),
            _p("radio_smooth_sigma", "Radio smoothing sigma", "number", flag="--radio-smooth-sigma", minimum=0, advanced=True),
            _p("dpi", "DPI", "integer", default=150, flag="--dpi", minimum=72, maximum=1200),
            OUTPUT_DIR,
        ),
        outputs=(_out("overlay", "DEM radio overlay", "image"),),
        output_flag="--output-dir",
        output_parameter="output_dir",
        required_any=("radio_file", "radio_dir"),
        page_templates=("source-trajectory",),
    ),
    FunctionSpec(
        "composer-export",
        "Image Composer Export",
        "Trajectory & Media",
        "Render a schema-1 Image Composer project through the shared worker.",
        "solar_apps.frontends.app_v1.composer_worker",
        parameters=(
            _p("project", "Composer project", "file", required=True, flag="--project", extensions=(".json",)),
            _p("mode", "Export mode", "enum", default="static", flag="--mode", choices=("static", "sequence")),
            _p("output_file", "Output", "file", required=True, flag="--output"),
            _p("scale", "Scale", "integer", default=1, flag="--scale", minimum=1, maximum=8),
            _p("fps", "Frame rate", "number", default=5.0, flag="--fps", minimum=0.1, maximum=120, unit="fps"),
            _p("save_png_frames", "Save PNG frames", "boolean", default=False, flag="--save-png-frames"),
        ),
        inputs=(_in("images", "Images", "image"),),
        outputs=(_out("media", "Composed media", "image", "media"),),
        allowed_roots_flag="--allowed-roots",
        page_templates=("image-composer",),
    ),
)

FUNCTIONS = (*FUNCTIONS, *radio_workspace_functions(FUNCTIONS))

DEFAULT_FUNCTION_CATALOG = FunctionCatalog(FUNCTIONS)

PAGE_TEMPLATE_FUNCTIONS: dict[str, tuple[str, ...]] = {
    "workbench": tuple(function.function_id for function in FUNCTIONS),
    "radio-workspace": tuple(
        function.function_id
        for function in FUNCTIONS
        if "radio-workspace" in function.page_templates
    ),
    "image-viewer": ("image-discover", "aia-process", "hmi-overlay"),
    "image-composer": ("composer-export",),
    "bad-frame-review": ("bad-frame-discover",),
    "source-map": ("source-map-render", "gaussian-fit", "center-extraction"),
    "dart-spectrogram": ("dart-spectrum", "drift-rate", "newkirk-diagnostics"),
    "roi-lightcurve": ("roi-lightcurve",),
    "radio-composite": ("source-map-render", "dart-spectrum", "radio-composite"),
    "source-trajectory": (
        "center-extraction",
        "trajectory-export",
        "dem-radio-overlay",
    ),
}


def page_template(module_id: str) -> AppV1FlowV1:
    try:
        function_ids = PAGE_TEMPLATE_FUNCTIONS[module_id]
    except KeyError as exc:
        raise KeyError(f"Unknown page workflow template: {module_id}") from exc
    nodes = tuple(
        FlowNodeV1(
            node_id=f"node-{index}",
            function_id=function_id,
            parameters={},
            x=float(((index - 1) % 5) * 250),
            y=float(((index - 1) // 5) * 120),
        )
        for index, function_id in enumerate(function_ids, start=1)
    )
    edges: list[FlowEdgeV1] = []
    if module_id == "radio-composite":
        edges.extend(
            (
                FlowEdgeV1("node-1", "images", "node-3", "maps"),
                FlowEdgeV1("node-2", "spectrum", "node-3", "spectrum"),
            )
        )
    elif module_id == "dart-spectrogram":
        edges.extend(
            (
                FlowEdgeV1("node-1", "spectrum", "node-2", "spectrum"),
                FlowEdgeV1("node-2", "drift", "node-3", "drift"),
            )
        )
    elif module_id == "source-trajectory":
        edges.append(
            FlowEdgeV1("node-1", "centers", "node-2", "centers_input")
        )
    return AppV1FlowV1(
        flow_id=f"{module_id}-default",
        name=f"{module_id.replace('-', ' ').title()} Default",
        nodes=nodes,
        edges=tuple(edges),
        saved_at_utc=datetime.now(timezone.utc),
    )


__all__ = [
    "DEFAULT_FUNCTION_CATALOG",
    "FUNCTIONS",
    "PAGE_TEMPLATE_FUNCTIONS",
    "page_template",
]
